name: "[C]ontinuous [I]ntegration"

on:
  workflow_dispatch: # Allows triggering the workflow manually in GitHub UI
  pull_request:
  push:
    branches: ["main"]


# If another push to the same PR or branch happens while this workflow is still running,
# cancel the earlier run in favor of the next run.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  terraform_validate:
    name: terraform validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/terraform_install
      - uses: ./.github/actions/terraform_init
      - uses: ./.github/actions/terraform_fmt-check
      - uses: ./.github/actions/terraform_validate
