name: "[C]ontinuous [I]ntegration: PR - helm"

on:
  workflow_dispatch: # Allows triggering the workflow manually in GitHub UI
  pull_request:
    paths:
      - helm/**

# If another push to the same PR or branch happens while this workflow is still running,
# cancel the earlier run in favor of the next run.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  helm_ci:
    name: helm
    uses: ./.github/workflows/helm_ci.yml
