name: "[C]ontinuous [I]ntegration: main"

on:
  workflow_dispatch: # Allows triggering the workflow manually in GitHub UI
  push:
    branches: ["main"]

# If another push to the same PR or branch happens while this workflow is still running,
# cancel the earlier run in favor of the next run.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  npm_lint:
    name: npm
    uses: ./.github/workflows/npm_lint.yml

  python_ci:
    name: uv
    needs: npm_lint
    uses: ./.github/workflows/uv_ci.yml

  terraform_ci:
    name: terraform
    needs: python_ci
    uses: ./.github/workflows/terraform_ci.yml

  docker_ci:
    name: docker
    needs: python_ci
    uses: ./.github/workflows/docker_ci.yml

  helm_lint:
    name: helm
    needs: docker_ci
    uses: ./.github/workflows/helm_ci.yml
