name: npm lint

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  npm_lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: ./.github/actions/checkout
      - uses: ./.github/actions/node_setup
      - uses: ./.github/actions/npm_install

      - name: run lint
        run: npm run lint
