name: "[C]ontinuous [I]ntegration: terraform"

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  terraform_ci:
    name: terraform fmt check & validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/terraform_setup
      - uses: ./.github/actions/terraform_init
      - uses: ./.github/actions/terraform_fmt-check
      - uses: ./.github/actions/terraform_validate
