name: python CI

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  verify:
    runs-on: ubuntu-latest
    name: poe ci
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/uv_setup

      # - name: Install dependencies
      #   run: |
      #     curl -LsSf https://astral.sh/uv/install.sh | sh
      #     uv venv
      #     uv pip install -r pyproject.toml

      # - name: Lint with ruff
      #   run: |
      #     uv pip install ruff
      #     uv run ruff check .

      # - name: Lint with mypy
      #   run: |
      #     uv pip install mypy
      #     uv run mypy --strict src/

      # - name: Check README spelling
      #   uses: codespell-project/actions-codespell@v2
      #   with:
      #     ignore_words_file: .codespellignore
      #     path: README.md

      # - name: Check code spelling
      #   uses: codespell-project/actions-codespell@v2
      #   with:
      #     ignore_words_file: .codespellignore
      #     path: src/

      # - name: Run tests with pytest
      #   run: |
      #     uv pip install pytest
      #     uv run pytest tests/unit_tests

      - uses: ./.github/actions/uv_python_install

      - name: uv tool install
        run: bash scripts/uv/tool/install.ba.sh

      - uses: ./.github/actions/uv_sync

      - name: poe ci
        run: uv run poe ci
